language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE-TOKEN
  project: "bayona-me"
  local-dir: dist/
  message: "Deploy release ${TRAVIS_TAG}"